### ISSUE TITLE
[Rabbitmq] Add Jobi YAML queues configurations

### ISSUE THREAD

**Issue by XZzYassin** [Rudy-Zidan/jobi#7]
Should contain the following keys per queue:
```yaml
calculators:
   durable: true || false
   prefetch: 10 || 5
   ack: true || false
```
- durable [Boolean]
- prefetch [Integer]
- ack [Boolean]
